services:
  - type: web
    name: ai-terminal
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python start_server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: GEMINI_API_KEY
        value: AIzaSyCknv4gzEzQj1ThRx8uEs_w1IqAo4dxC9c
